package game;

import java.util.ArrayList;

import items.Item;
import javafx.scene.image.Image;
/**
 * 
 * An interface to allow a Game world to interact with the game controllers
 * 
 * @author colinauyeung
 *
 */
public interface GameWorld {
	
	/**
	 * Changing the world state based on an input
	 * 
	 * @param input
	 * 		A string to the world to change the game state
	 * 
	 * @return 
	 * 		An Event generated by the game state
	 */
	public Event runTurn(String input);
	
	/**
	 * Game World loads a new world state based on a string
	 * 
	 * @param next
	 * 		A string containing information for generating a world
	 */
	public void nextWorld(String next);
	
	/**
	 * Returns a 3D arraylist of javafx image objects represents tiles in the 
	 * game world
	 * 
	 * @param size
	 *            the dimensions of map to display
	 * @return a 3D arraylist of strings containing paths to the game sprites
	 */
	public ArrayList<ArrayList<ArrayList<Image>>> getImageSprites(int mapsize);
	
	/**
	 * Returns a 2D arraylist of strings that that represents tiles in the 
	 * game world
	 * 
	 * @return a 2D arraylist of strings that represent the game world 
	 * 
	 */
	public ArrayList<ArrayList<String>> getTextSprites();
	
	/**
	 * Returns a arraylist of items in the player inventory
	 * 
	 * @return a arraylist of items
	 */
	public ArrayList<Item> getInventory();
	
	public Item getPlayerWeapon();
	
	public Item getPlayerArmour();
		
}
